"""add camera runtime telemetry

Revision ID: 5b79ec24f393
Revises: 9ff4cf7aa086
Create Date: 2026-09-26 11:19:43.718664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b79ec24f393'
down_revision: Union[str, Sequence[str], None] = '9ff4cf7aa086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_runtime', sa.Column('camera_name', sa.String(length=150), nullable=True))
    op.add_column('device_runtime', sa.Column('camera_source', sa.String(length=255), nullable=True))
    op.add_column('device_runtime', sa.Column('camera_width', sa.Integer(), nullable=True))
    op.add_column('device_runtime', sa.Column('camera_height', sa.Integer(), nullable=True))
    op.add_column('device_runtime', sa.Column('camera_fps', sa.Float(), nullable=True))
    op.add_column('device_runtime', sa.Column('camera_frame_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_runtime', 'camera_frame_id')
    op.drop_column('device_runtime', 'camera_fps')
    op.drop_column('device_runtime', 'camera_height')
    op.drop_column('device_runtime', 'camera_width')
    op.drop_column('device_runtime', 'camera_source')
    op.drop_column('device_runtime', 'camera_name')
    # ### end Alembic commands ###
