"""add edge device runtime

Revision ID: 9ff4cf7aa086
Revises: f8d60acb4d98
Create Date: 2026-09-26 02:37:58.020805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff4cf7aa086'
down_revision: Union[str, Sequence[str], None] = 'f8d60acb4d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_runtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('edge_version', sa.String(length=50), nullable=True),
    sa.Column('current_mode', sa.String(length=100), nullable=True),
    sa.Column('current_mission_id', sa.Integer(), nullable=True),
    sa.Column('camera_status', sa.String(length=30), nullable=False),
    sa.Column('coral_status', sa.String(length=30), nullable=False),
    sa.Column('pixhawk_status', sa.String(length=30), nullable=False),
    sa.Column('gps_status', sa.String(length=30), nullable=False),
    sa.Column('gps_fix', sa.Integer(), nullable=True),
    sa.Column('satellites', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('cpu_temperature', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.add_column('devices', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('api_key_prefix', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'api_key_prefix')
    op.drop_column('devices', 'api_key_hash')
    op.drop_table('device_runtime')
    # ### end Alembic commands ###
